# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobileNum', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('roofType', models.CharField(max_length=50)),
                ('roofHeight', models.CharField(max_length=20)),
                ('electricityBoard', models.CharField(max_length=100)),
                ('otherDetails', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('create_tmp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
